http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  session_key: "juigeruhgrehgu8reg8348tgt438ugt43u8t4u8tu48t438ut4g9rqer9qer7tgweqhrew8r4ew389yhqr397r32qut9ndeugbrfegfgbh"
db:
  storage_path: "./database/storage.db"